name: CI
on:
  merge_group: {}
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  required:
    name: "Required Checks: CI"
    if: ${{ always() }}
    needs:
      - verify-author
      - changed-files
      - actionlint
      - ghalint
      - zizmor
      - build
      - commitlint
      - editorconfig
      - eslint
      - prettier
      - prisma
      - test
      - typecheck
      - yamllint
    runs-on: ubuntu-slim
    timeout-minutes: 60
    steps:
      - name: Fail if any required jobs failed or cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
  verify-author:
    name: Verify author
    environment: ${{ github.event_name == 'pull_request' &&
      endsWith(github.event.pull_request.user.login, '[bot]') &&
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      contains(github.event.pull_request.labels.*.name, 'github_actions') && 'ci' || null }}
    runs-on: ubuntu-slim
    timeout-minutes: 60
    steps:
      - name: Author has been verified
        run: exit 0
  changed-files:
    name: Get changed files
    if: ${{ github.event_name == 'pull_request' }}
    needs: verify-author
    runs-on: ubuntu-slim
    timeout-minutes: 60
    permissions:
      contents: read
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      actions: ${{ steps.changed-files.outputs.actions_any_modified == 'true' }}
      eslint: ${{ steps.changed-files.outputs.eslint_any_modified == 'true' }}
      prettier: ${{ steps.changed-files.outputs.prettier_any_modified == 'true' }}
      prisma: ${{ steps.changed-files.outputs.prisma_any_modified == 'true' }}
      test: ${{ steps.changed-files.outputs.test_any_modified == 'true' }}
      typecheck: ${{ steps.changed-files.outputs.typecheck_any_modified == 'true' }}
      yamllint: ${{ steps.changed-files.outputs.yamllint_any_modified == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          persist-credentials: true
      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files_yaml: |
            common: &common
              - .github/workflows/ci.yml
            dependencies: &dependencies
              - package.json
              - pnpm-lock.yaml
            app: &app
              - *common
              - *dependencies
              - app/**
              - prisma/**
              - public/**
              - react-router.config.*
              - tailwind.config.*
              - tsconfig.json
              - vite.config.*
            actions:
              - "**/action.{yaml,yml}"
              - ".github/workflows/*.{yaml,yml}"
            eslint:
              - *app
              - "**/*.{cjs,js,jsx,mjs,ts,tsx}"
              - eslint.config.*
            prettier:
              - *app
              - "**/*.{cjs,css,js,json,jsx,mjs,ts,tsx,yaml,yml}"
              - prettier.config.*
            prisma:
              - *common
              - *dependencies
              - .prisma-case-format
              - prisma/**
            test:
              - *app
              - .storybook/**
              - vitest.*
            typecheck:
              - *app
              - "**/*.{ts,tsx}"
            yamllint:
              - *common
              - "**/*.{yaml,yml}"
  actionlint:
    name: actionlint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run actionlint
        uses: ponko2/actions/actionlint@957f0cbafbd663effe5868464cbea63d7aca5067 # v1.3.1
  ghalint:
    name: ghalint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-slim
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run ghalint
        uses: ponko2/actions/ghalint@957f0cbafbd663effe5868464cbea63d7aca5067 # v1.3.1
  zizmor:
    name: zizmor
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.actions == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: ponko2/actions/zizmor@957f0cbafbd663effe5868464cbea63d7aca5067 # v1.3.1
  build:
    name: Build
    if: ${{ always() && !failure() && !cancelled() && needs.test.result == 'success' }}
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Run generate
        run: pnpm run generate
      - name: Run build
        run: pnpm run build
  commitlint:
    name: commitlint
    if: ${{ github.event_name == 'pull_request' }}
    needs: verify-author
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
          filter: blob:none
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Validate all commits from PR
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: pnpm exec commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --verbose
  editorconfig:
    name: EditorConfig
    needs: verify-author
    runs-on: ubuntu-slim
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up EditorConfig checker
        uses: editorconfig-checker/action-editorconfig-checker@4b6cd6190d435e7e084fb35e36a096e98506f7b9 # v2.1.0
      - name: Run EditorConfig checker
        run: editorconfig-checker
  eslint:
    name: ESLint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.eslint == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Run generate
        run: pnpm run generate
      - name: Add problem matchers
        run: echo "::add-matcher::.github/eslint-matcher.json"
      - name: Run ESLint
        run: pnpm run lint:eslint
  prettier:
    name: Prettier
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.prettier == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm run lint:prettier
  prisma:
    name: Prisma
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.prisma == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Run prisma format
        run: pnpm exec prisma format
      - name: Run prisma case format
        run: pnpm exec prisma-case-format --file prisma/schema.prisma
      - name: Validate Prisma schema is formatted
        run: git diff --exit-code
  test:
    name: Test
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.test == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.57.0-noble@sha256:3bed4b1a12f2338642f3d8cba28e291deef3c66bd4a964bbeb3e57bbff511dbd
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      matrix:
        node-version:
          - lts/*
          - lts/-1
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install
      - name: Run generate
        run: pnpm run generate
      - name: Run test
        run: pnpm test
  typecheck:
    name: typecheck
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.typecheck == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm install
      - name: Run generate
        run: pnpm run generate
      - name: Add problem matchers
        run: echo "::add-matcher::.github/tsc-matcher.json"
      - name: Run tsc
        run: pnpm run typecheck
  yamllint:
    name: yamllint
    if: ${{ always() && !failure() && !cancelled() &&
      (needs.changed-files.result == 'skipped' || needs.changed-files.outputs.yamllint == 'true') }}
    needs: changed-files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run yamllint
        run: yamllint --format=github --strict .
